server:
    port: 8888
    compression:
        enabled: true
        mime-types: text/html,text/xml,text/plain,text/css,application/javascript,application/json
        min-response-size: 1024
    session:
        timeout: 1800
spring:
   profiles.active: dev
   freemarker.cache: false
   resources.cache-period: 0
   datasource:
         url: jdbc:mysql://127.0.0.1:3306/test?characterEncoding=utf8&useSSL=false
         username: root
         password: root
         hikari:
             minimumIdle: 5
             maximumPoolSize: 15
             data-source-properties:
                 cachePrepStmts: true
                 prepStmtCacheSize: 250
                 prepStmtCacheSqlLimit: 2048
                 useServerPrepStmts: true
#  jpa配置
   jpa:
      show-sql: true
      hibernate:
          # Hibernate DDL  auto: create, create-drop, update, validate
          ddl-auto: validate
      properties:
          hibernate.dialect: org.hibernate.dialect.MySQL5Dialect
          hibernate.current_session_context_class: org.springframework.orm.hibernate4.SpringSessionContext


